### ISSUE TITLE
server ile uygulama arasındaki bağlantı kurulamadı

### ISSUE THREAD

**Issue by Selahattinn** [Selahattinn/Spodia-Android#1]
server ile uygulama arasındaki bağlantı kurulamadı.

**Comment by furkansahinfs** [comment]
Nasiii dıddıırırıdııddırı. 
Uygulama Google serverı ile bağlantı kurdu.Response aldı. Bizim serverla bağlantıda sertifika hatası devam ediyor.

**Comment by Selahattinn** [comment]
kuruldu.başardık reis
