### ISSUE TITLE
Şifremi unuttum kısmı xmlde olmasına rağmen uygulamada gözükmüyor.

### ISSUE THREAD

**Issue by Selahattinn** [Selahattinn/Spodia-Android#2]
Şifremi unuttum kısmı xmlde olmasına rağmen uygulamada gözükmüyor. sorunu çözemedim

![a90ee10b36f26393f050aa13456ca45b](https://user-images.githubusercontent.com/33727208/70177634-cd8e4480-16eb-11ea-93d1-f6033028788d.png)

**Comment by furkansahinfs** [comment]
Hata giderildi. Çözümü :

Xml dosyasında app:src="drawable/logo.png" tarzında ifade kullanmayın.
Her zaman android:src="drawable/logo.png" kullanın.

Ayrıca drawable-xxxhdpi dolu olacak. Onun dışında mipmap-xxxhdpi klasörü de dolu olacak.

Eğer ki android:src="drawable/logo.png" olduğu halde gözükmüyor ise "mipmap/logo.png" deneyin.

Ayrıca tools:text kullanmayın. android:text kullanın
